name: health
description: "NextZen Healthcare Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_tts: ^4.0.2
  image_picker: ^1.1.2
  webview_flutter: ^4.10.0
  camera: ^0.11.0+2
  flutter_pdfview: ^1.3.3
  flutter_localization: ^0.2.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  printing: ^5.13.3
  pdf: ^3.11.1
  path_provider: ^2.1.4
  table_calendar: ^3.1.2
  flutter_signature_pad: ^3.0.1
  permission_handler:
  http_parser: ^4.0.2
  http: ^1.2.2
  mime: ^2.0.0
  path: ^1.9.0
  google_mlkit_text_recognition: ^0.8.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true  # Add this line to enable code generation

  assets:
    - assets/images/
    - assets/data/Blood Test Report.pdf
    - assets/data/Urine Test Report.pdf
    - assets/data/Drug Prescription.pdf
    - assets/data/Eye Arc Test Report.pdf
    - assets/data/Dental Report.pdf
    - assets/data/Xray Report.pdf
    - assets/data/DEXA Scan Report.pdf
    - assets/data/Echo Test Report.pdf
    - assets/data/Ultrasound Test Report.pdf
    - assets/data/Diet Plan.pdf
    - lib/l10n/

flutter_gen_l10n:
  enabled: true
  arb-dir: lib/l10n
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  template-arb-file: app_en.arb
  unconverted-messages-file: untranslated_messages.txt

